# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true

# edit here to achieve your personal greatness
url: http://kiranbollepalli9.github.io/
baseurl: /kiran/
title: Kiran Bollepalli
author: Kiran Bollepalli
description: Personal blog and resume
avatar: profile.png
email: kiranbollepalli@gmail.com
github: myjekyll/kiranbollepalli9 # username
twitter: username
linkedin: username
stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
